[[constraint]]
  name = "github.com/devopsfaith/krakend"
  version = "0.7.0"

[[constraint]]
  name = "github.com/xeipuuv/gojsonschema"
  version = "1.0.0"

[prune]
  go-tests = true
  unused-packages = true
